-- migrate:up

INSERT INTO gps (id_gps, nombre) VALUES (1, 'GPS COMSATEL');
INSERT INTO gps (id_gps, nombre) VALUES (2, 'GPS PANDERO');
INSERT INTO gps (id_gps, nombre) VALUES (3, 'GPS TRACKLINK  OK');
INSERT INTO gps (id_gps, nombre) VALUES (4, 'GPS OK');
INSERT INTO gps (id_gps, nombre) VALUES (5, 'GPS COMSATEL OK');
INSERT INTO gps (id_gps, nombre) VALUES (6, 'GPS TRACKLINK OK');
INSERT INTO gps (id_gps, nombre) VALUES (7, 'NO APLICA CAMPAÑA');
INSERT INTO gps (id_gps, nombre) VALUES (8, 'GPS TRACKLINK');
INSERT INTO gps (id_gps, nombre) VALUES (9, 'GPS COMSATEL  OK');
INSERT INTO gps (id_gps, nombre) VALUES (10, 'GPS COMSATEL 16/7');
INSERT INTO gps (id_gps, nombre) VALUES (11, 'SUPRA  /NO APLICA CAMPAÑA');
INSERT INTO gps (id_gps, nombre) VALUES (12, 'GPS PANDERO  OK');
INSERT INTO gps (id_gps, nombre) VALUES (13, 'GPS PANDERO OK');
INSERT INTO gps (id_gps, nombre) VALUES (14, 'GPS COMSATELOK');
INSERT INTO gps (id_gps, nombre) VALUES (15, 'GPS HUNTER');
INSERT INTO gps (id_gps, nombre) VALUES (16, 'SUPRA OK');
INSERT INTO gps (id_gps, nombre) VALUES (17, 'SUPRA INSTALADO');
INSERT INTO gps (id_gps, nombre) VALUES (18, 'TAPA RETRACTIL DE ALUMINIO MANUAL OK');
INSERT INTO gps (id_gps, nombre) VALUES (19, 'COMPRA UNDERCOATING/SUPRA');
INSERT INTO gps (id_gps, nombre) VALUES (20, 'GPS MAQUISISTEMAS');
INSERT INTO gps (id_gps, nombre) VALUES (21, 'SE PIDE CAMPAÑA');
INSERT INTO gps (id_gps, nombre) VALUES (22, 'SE REGALA 1ER MANT VB ERICK X SUNROOF QUE NO CERRABA');
INSERT INTO gps (id_gps, nombre) VALUES (23, 'GPS PROTEMAX');
INSERT INTO gps (id_gps, nombre) VALUES (24, 'GPS TRACKLING');
INSERT INTO gps (id_gps, nombre) VALUES (25, 'SUPRAOK');
INSERT INTO gps (id_gps, nombre) VALUES (26, 'GPS HUNTER OK');
INSERT INTO gps (id_gps, nombre) VALUES (27, 'SUPRA');
INSERT INTO gps (id_gps, nombre) VALUES (28, 'UNDERCOATING');
INSERT INTO gps (id_gps, nombre) VALUES (29, 'GPS TRACKLINKOK');
INSERT INTO gps (id_gps, nombre) VALUES (30, 'GPS TRACLKINKOK');
INSERT INTO gps (id_gps, nombre) VALUES (31, 'GPS PROTEMAXOK');
INSERT INTO gps (id_gps, nombre) VALUES (32, 'GPSOK');
INSERT INTO gps (id_gps, nombre) VALUES (33, 'HUNTEROK');
INSERT INTO gps (id_gps, nombre) VALUES (34, 'GPS TRACJLINKOK');
INSERT INTO gps (id_gps, nombre) VALUES (35, '.');
INSERT INTO gps (id_gps, nombre) VALUES (36, 'GPS PANDEROOK');
INSERT INTO gps (id_gps, nombre) VALUES (37, 'GPS HUNTEROK');
INSERT INTO gps (id_gps, nombre) VALUES (38, 'COMPRA NANOCERAMICO 3M 390$OK');
INSERT INTO gps (id_gps, nombre) VALUES (39, 'PAGO SUPRAOK');
INSERT INTO gps (id_gps, nombre) VALUES (40, 'GPS HUNTER AUTOPLANOK');
INSERT INTO gps (id_gps, nombre) VALUES (41, 'GPS COMSATEL+COORDINAR CON CLIENTE');
INSERT INTO gps (id_gps, nombre) VALUES (42, 'GPS EURORENTING');
INSERT INTO gps (id_gps, nombre) VALUES (43, 'NO NECESITA GPS');
INSERT INTO gps (id_gps, nombre) VALUES (44, 'TRACKLINKOK');
INSERT INTO gps (id_gps, nombre) VALUES (45, 'COMSATEL');
INSERT INTO gps (id_gps, nombre) VALUES (46, 'HUNTER 6/1');
INSERT INTO gps (id_gps, nombre) VALUES (47, 'HUNTER');
INSERT INTO gps (id_gps, nombre) VALUES (48, 'GPS NO APLICA');
INSERT INTO gps (id_gps, nombre) VALUES (49, 'COMSATELOK');
INSERT INTO gps (id_gps, nombre) VALUES (50, 'GPS TRACKLINKCOORDINAR CON EL CLIENTE');
INSERT INTO gps (id_gps, nombre) VALUES (51, 'GPS TRACLKING');
INSERT INTO gps (id_gps, nombre) VALUES (52, 'COMSATEL 6/1');
INSERT INTO gps (id_gps, nombre) VALUES (53, 'COMSATEL 7/1');

-- migrate:down
DELETE FROM gps;
