-- migrate:up

INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE', 1);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO (SE FUA A PANDERO EL 30/05)', 2);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+ROTATIVA', 3);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+SOS REVISAR EL LIQUIDO DE FRENOS', 4);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO CAMACHO', 5);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO SI', 6);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA', 7);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO SHOWROOM', 8);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVA+NO ENTREGAR PROBLEMAS CON RETOMA', 9);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+SLA TAPA DE ESPEJO RETROVISOR DEL. RH PRESENTA ARAÑON', 10);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO', 11);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('CAMACHO', 12);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO SHOWROOM+ROTATIVA', 13);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+UNIDAD EN TRAVESIA', 14);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+UNIDAD EN TRAVESIA+FT15/07', 15);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+DUA ERRADA AZUL', 16);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA (SE FUE A PANDERO 26/06)', 17);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+DISPONIBLE 09/07', 18);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO SI+ROTATIVA', 19);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVA', 20);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO SI+FALTA LIBRETA', 21);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA (SE FUE A PANDERO EL 03/06)', 22);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO+7GL', 23);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO CAMACHO+FT 30/07', 24);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('FRONTIS', 25);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 5GL+ROTATIVA', 26);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO CAMACHO+GARANTIA PUERTO USB', 27);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE-ENTREGAR 8/8 REF ERICK', 28);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ENTREGAR 14/8 ROTATIVAS-DUA SOS', 29);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('CAMACHO+25C17', 30);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO', 31);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVAS-ASESOR PROMETE 13/8', 32);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE-ENTREGAR 13/8', 33);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO + 6GLS', 34);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGAR 15/8', 35);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVAS ENTREGAR 19/8', 36);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+PLACA FINAL PARA 19/8', 37);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVAS+ENTREGAR 19/8', 38);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHER+ROTATIVAS 19/8', 39);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ROTATIVAS 19/8', 40);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SLA+ENTREGAR EL 15/8', 41);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SLA+ROTATIVAS 20/8', 42);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO+PLACA FINAL', 43);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+CHECK PRENDIDO INGRESAR A TALLER+PLACA FINAL', 44);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+ROTATIVAS 21/8', 45);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ROTATIVAS', 46);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE- ENTREGAR 21/8', 47);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGAR 21/8', 48);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE ENTREGAR 21/8', 49);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+PLACA FINAL', 50);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE-CARTA KM ALTO', 51);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE FT 29/08 CLIENTE DE ICA', 52);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+TRABAJO EN CAPOT 15/8- CARTA KM ALTO', 53);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+25C17', 54);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COOCHERA+ROTATIVA', 55);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO COCHERA ARAÑON EN EL PARACHOQUE DELANTERO', 56);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE,UNIDAD QUEDA LISTA EL 22.08', 57);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+SE PRESTO A TALLER PARA DESPIECE (REGULARIZADO 25/07) PROCEDER A LA VENTA', 58);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+ROTATIVA FT 05/08', 59);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO+RETORNA EL 18/03 ATENTO PARA PROCEDER CON SU 2DO PDI,', 60);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 7GL', 61);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE, LLEGO SIN LIBRETA RECLAMAR A SLA', 62);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('EN MOLINA', 63);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('UNIDAD EN PATIO SI', 64);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+RETIRO DIRECTO PARA SENSOR(REGULARIZADO)', 65);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO', 66);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+FT MARTES 16 SET', 67);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+FT 17/09 ROTATIVA', 68);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 5GL', 69);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE, PRESTAMO TALLER', 70);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('CAMACHO PATIO', 71);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+PRECIO FT COMPRA ERRADA PEDIR A LA MARCA LA NC FC01-0001372', 72);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+UNIDAD PARA DESPICE 5 PIEZAS, LLEGA FINES DE ABRIL TALLER-REPUESTO/NO LE PRESTE ESTA UNIDAD-BATERIA FALLANDO SE MANDO CORREO A TALLER, ABOLLADURA DEBAJO TAPA DE COMBUSTIBLE', 73);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+1° OCTUBRE NO CONSIDERAR EN LA ENCUESTA, LO LLAME LO PROMETI PARA EL 20 OCT', 74);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+PLUMILLA LADO DER NO SUBE', 75);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL', 76);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+RECLAMAR KM ALTO', 77);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO+PLACA FINAL PEDIR ACCESORIOS A MAURICIO', 78);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+SIN LOGO M7+ENTREGA VIERNES 31 OCT', 79);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO COCHERA+HACER CAMPAÑA', 80);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGA MIERCOLES 29-10', 81);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SLA+ENTREGA MARTES 04 NOV', 82);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+NO ENTREGAR PEDIR VB SANTANDER', 83);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+ENTREGA VIERNES 07 NOV', 84);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO CAMACHO+FINAL ENTREGA 20 NOV', 85);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO+RVISAR ESTA ARAÑADO PARTE TRASERO LADO DERECHO+ENTREGA SAB 08 NOV', 86);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('CAMACHO PATIO+ROTATIVA ENTREGA 14 NOV', 87);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+SLA MOLDURA PLATA DE PARACHOQUE DELANTER', 88);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+SIN LOGO M7', 89);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+ROTATIVA', 90);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('CAMACHO+RETIRO DIRECTO 6GL', 91);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+ENTREGA VIERNES 21 NOV', 92);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+ENTREGA MARTES 18, 3PM', 93);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGA JUEVES 20 NOV', 94);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVA CUMPLE MIERCOLES 19 NOV', 95);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+ENTREGA VIERNES 28 NOV', 96);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ABOLLADURA EN CAPOT', 97);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGA JUEVES 04 NOV', 98);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('CAMACHO+OBS QUIÑE EN LA PARTE DELANTERA IZQUIERDA. QUIÑE EN LA PARTE DERECHA ATRÁS.', 99);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('COCHERA+SIN LOGO M7', 100);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+ENTREGA MIERCOLES 10-DIC', 101);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVA VIERNES 19 DIC', 102);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVA AMIGO ALONZO+19 DICSLA MASCARA DELANTERA QUIÑADA, NO PAGAR ALMACEN', 103);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+RT CLIENTE DE PROVINCIA', 104);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+ENTREGA LUNES 22-DIC', 105);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL+CLIENTE DE LIMA RT', 106);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRODIRECTO 6GL', 107);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGA VIERNES 12 DIC', 108);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+UCAYALI RT 29DIC', 109);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GLS', 110);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+FINAL', 111);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ENTREGA 5/01', 112);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PATIO LM', 113);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DIRECTO 6GL/EXH LM', 114);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('SAN ISIDRO+CAMPAÑA', 115);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ SLA LIBERA 31/12 + ENTREGAR EL 7/01', 116);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('RETIRO DRECTO + 6GLS', 117);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+SLA UNIDDA NO ARRANCA REPUESTO IMPORTACIÓN ETA 2/01+ENTREGAR EL 7/1', 118);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ENTREGAR 12/01+SLA PDI 31/12', 119);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + CLIENTE LUCERO', 120);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ROTATIVAS 9/1+CORREO PARA AGERGAR TAPA DE TOLVA', 121);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+PEDIR ERICK+ROTATIVAS', 122);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ROTATIVAS 9/1', 123);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ ROTATIVAS', 124);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVAS', 125);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ ENTREGA 8/01', 126);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('PROBLEMAS', 127);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVAS 7/1', 128);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+TRAER', 129);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ENTREGAR 13/1', 130);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE+ROTATIVAS 13/1', 131);
INSERT INTO ubicaciones (ubicacion, distritos_id) VALUES ('ATE + ENTREGAR 15/1 ROTATIVAS', 132);

-- migrate:down
DELETE FROM ubicaciones;
