-- migrate:up

INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (1,'ATE', 1);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (2,'SAN ISIDRO (SE FUA A PANDERO EL 30/05)', 2);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (3,'COCHERA+ROTATIVA', 3);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (4,'COCHERA+SOS REVISAR EL LIQUIDO DE FRENOS', 4);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (5,'PATIO CAMACHO', 5);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (6,'PATIO SI', 6);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (7,'COCHERA', 7);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (8,'SAN ISIDRO SHOWROOM', 8);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (9,'ATE+ROTATIVA+NO ENTREGAR PROBLEMAS CON RETOMA', 9);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (10,'COCHERA+SLA TAPA DE ESPEJO RETROVISOR DEL. RH PRESENTA ARAÑON', 10);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (11,'RETIRO DIRECTO', 11);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (12,'CAMACHO', 12);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (13,'SAN ISIDRO SHOWROOM+ROTATIVA', 13);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (14,'ATE+UNIDAD EN TRAVESIA', 14);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (15,'ATE+UNIDAD EN TRAVESIA+FT15/07', 15);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (16,'ATE+DUA ERRADA AZUL', 16);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (17,'COCHERA (SE FUE A PANDERO 26/06)', 17);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (18,'ATE+DISPONIBLE 09/07', 18);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (19,'PATIO SI+ROTATIVA', 19);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (20,'ATE+ROTATIVA', 20);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (21,'PATIO SI+FALTA LIBRETA', 21);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (22,'COCHERA (SE FUE A PANDERO EL 03/06)', 22);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (23,'RETIRO DIRECTO+7GL', 23);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (24,'PATIO CAMACHO+FT 30/07', 24);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (25,'FRONTIS', 25);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (26,'RETIRO DIRECTO 5GL+ROTATIVA', 26);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (27,'PATIO CAMACHO+GARANTIA PUERTO USB', 27);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (28,'ATE-ENTREGAR 8/8 REF ERICK', 28);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (29,'ENTREGAR 14/8 ROTATIVAS-DUA SOS', 29);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (30,'CAMACHO+25C17', 30);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (31,'SAN ISIDRO', 31);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (32,'ATE+ROTATIVAS-ASESOR PROMETE 13/8', 32);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (33,'ATE-ENTREGAR 13/8', 33);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (34,'RETIRO DIRECTO + 6GLS', 34);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (35,'ATE+ENTREGAR 15/8', 35);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (36,'ATE+ROTATIVAS ENTREGAR 19/8', 36);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (37,'ATE+PLACA FINAL PARA 19/8', 37);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (38,'ATE+ROTATIVAS+ENTREGAR 19/8', 38);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (39,'COCHER+ROTATIVAS 19/8', 39);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (40,'ATE + ROTATIVAS 19/8', 40);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (41,'SLA+ENTREGAR EL 15/8', 41);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (42,'SLA+ROTATIVAS 20/8', 42);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (43,'PATIO+PLACA FINAL', 43);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (44,'COCHERA+CHECK PRENDIDO INGRESAR A TALLER+PLACA FINAL', 44);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (45,'COCHERA+ROTATIVAS 21/8', 45);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (46,'ATE + ROTATIVAS', 46);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (47,'ATE- ENTREGAR 21/8', 47);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (48,'ATE+ENTREGAR 21/8', 48);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (49,'ATE ENTREGAR 21/8', 49);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (50,'ATE+PLACA FINAL', 50);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (51,'ATE-CARTA KM ALTO', 51);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (52,'ATE FT 29/08 CLIENTE DE ICA', 52);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (53,'ATE+TRABAJO EN CAPOT 15/8- CARTA KM ALTO', 53);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (54,'COCHERA+25C17', 54);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (55,'COOCHERA+ROTATIVA', 55);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (56,'SAN ISIDRO COCHERA ARAÑON EN EL PARACHOQUE DELANTERO', 56);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (57,'ATE,UNIDAD QUEDA LISTA EL 22.08', 57);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (58,'COCHERA+SE PRESTO A TALLER PARA DESPIECE (REGULARIZADO 25/07) PROCEDER A LA VENTA', 58);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (59,'COCHERA+ROTATIVA FT 05/08', 59);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (60,'SAN ISIDRO+RETORNA EL 18/03 ATENTO PARA PROCEDER CON SU 2DO PDI,', 60);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (61,'RETIRO DIRECTO 7GL', 61);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (62,'ATE, LLEGO SIN LIBRETA RECLAMAR A SLA', 62);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (63,'EN MOLINA', 63);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (64,'UNIDAD EN PATIO SI', 64);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (65,'COCHERA+RETIRO DIRECTO PARA SENSOR(REGULARIZADO)', 65);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (66,'PATIO', 66);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (67,'RETIRO DIRECTO 6GL+FT MARTES 16 SET', 67);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (68,'ATE+FT 17/09 ROTATIVA', 68);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (69,'RETIRO DIRECTO 5GL', 69);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (70,'ATE, PRESTAMO TALLER', 70);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (71,'CAMACHO PATIO', 71);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (72,'COCHERA+PRECIO FT COMPRA ERRADA PEDIR A LA MARCA LA NC FC01-0001372', 72);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (73,'COCHERA+UNIDAD PARA DESPICE 5 PIEZAS, LLEGA FINES DE ABRIL TALLER-REPUESTO/NO LE PRESTE ESTA UNIDAD-BATERIA FALLANDO SE MANDO CORREO A TALLER, ABOLLADURA DEBAJO TAPA DE COMBUSTIBLE', 73);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (74,'ATE+1° OCTUBRE NO CONSIDERAR EN LA ENCUESTA, LO LLAME LO PROMETI PARA EL 20 OCT', 74);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (75,'COCHERA+PLUMILLA LADO DER NO SUBE', 75);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (76,'RETIRO DIRECTO 6GL', 76);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (77,'ATE+RECLAMAR KM ALTO', 77);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (78,'SAN ISIDRO+PLACA FINAL PEDIR ACCESORIOS A MAURICIO', 78);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (79,'ATE+SIN LOGO M7+ENTREGA VIERNES 31 OCT', 79);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (80,'SAN ISIDRO COCHERA+HACER CAMPAÑA', 80);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (81,'ATE+ENTREGA MIERCOLES 29-10', 81);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (82,'SLA+ENTREGA MARTES 04 NOV', 82);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (83,'COCHERA+NO ENTREGAR PEDIR VB SANTANDER', 83);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (84,'COCHERA+ENTREGA VIERNES 07 NOV', 84);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (85,'PATIO CAMACHO+FINAL ENTREGA 20 NOV', 85);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (86,'PATIO+RVISAR ESTA ARAÑADO PARTE TRASERO LADO DERECHO+ENTREGA SAB 08 NOV', 86);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (87,'CAMACHO PATIO+ROTATIVA ENTREGA 14 NOV', 87);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (88,'ATE+SLA MOLDURA PLATA DE PARACHOQUE DELANTER', 88);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (89,'ATE+SIN LOGO M7', 89);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (90,'RETIRO DIRECTO 6GL+ROTATIVA', 90);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (91,'CAMACHO+RETIRO DIRECTO 6GL', 91);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (92,'RETIRO DIRECTO 6GL+ENTREGA VIERNES 21 NOV', 92);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (93,'RETIRO DIRECTO 6GL+ENTREGA MARTES 18, 3PM', 93);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (94,'ATE+ENTREGA JUEVES 20 NOV', 94);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (95,'ATE+ROTATIVA CUMPLE MIERCOLES 19 NOV', 95);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (96,'COCHERA+ENTREGA VIERNES 28 NOV', 96);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (97,'ATE+ABOLLADURA EN CAPOT', 97);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (98,'ATE+ENTREGA JUEVES 04 NOV', 98);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (99,'CAMACHO+OBS QUIÑE EN LA PARTE DELANTERA IZQUIERDA. QUIÑE EN LA PARTE DERECHA ATRÁS.', 99);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (100,'COCHERA+SIN LOGO M7', 100);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (101,'RETIRO DIRECTO 6GL+ENTREGA MIERCOLES 10-DIC', 101);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (102,'ATE+ROTATIVA VIERNES 19 DIC', 102);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (103,'ATE+ROTATIVA AMIGO ALONZO+19 DICSLA MASCARA DELANTERA QUIÑADA, NO PAGAR ALMACEN', 103);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (104,'RETIRO DIRECTO 6GL+RT CLIENTE DE PROVINCIA', 104);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (105,'RETIRO DIRECTO 6GL+ENTREGA LUNES 22-DIC', 105);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (106,'RETIRO DIRECTO 6GL+CLIENTE DE LIMA RT', 106);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (107,'RETIRODIRECTO 6GL', 107);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (108,'ATE+ENTREGA VIERNES 12 DIC', 108);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (109,'ATE+UCAYALI RT 29DIC', 109);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (110,'RETIRO DIRECTO 6GLS', 110);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (111,'ATE+FINAL', 111);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (112,'ATE + ENTREGA 5/01', 112);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (113,'PATIO LM', 113);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (114,'RETIRO DIRECTO 6GL/EXH LM', 114);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (115,'SAN ISIDRO+CAMPAÑA', 115);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (116,'ATE+ SLA LIBERA 31/12 + ENTREGAR EL 7/01', 116);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (117,'RETIRO DRECTO + 6GLS', 117);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (118,'ATE+SLA UNIDDA NO ARRANCA REPUESTO IMPORTACIÓN ETA 2/01+ENTREGAR EL 7/1', 118);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (119,'ATE + ENTREGAR 12/01+SLA PDI 31/12', 119);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (120,'ATE + CLIENTE LUCERO', 120);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (121,'ATE + ROTATIVAS 9/1+CORREO PARA AGERGAR TAPA DE TOLVA', 121);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (122,'ATE+PEDIR ERICK+ROTATIVAS', 122);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (123,'ATE + ROTATIVAS 9/1', 123);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (124,'ATE+ ROTATIVAS', 124);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (125,'ATE+ROTATIVAS', 125);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (126,'ATE+ ENTREGA 8/01', 126);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (127,'PROBLEMAS', 127);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (128,'ATE+ROTATIVAS 7/1', 128);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (129,'ATE+TRAER', 129);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (130,'ATE+ENTREGAR 13/1', 130);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (131,'ATE+ROTATIVAS 13/1', 131);
INSERT INTO ubicaciones (id_ubicacion,fubicacion, distritos_id) VALUES (132,'ATE + ENTREGAR 15/1 ROTATIVAS', 132);

-- migrate:down
DELETE FROM ubicaciones;
